add_newline = true

format = """
[ ](bold blue)
[â•­â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â”€â•®](bold blue)
[â”‚ [$username](brown)$hostname $time â”‚](bold blue)
[â”‚                               â•¯](bold blue)
[â”‚](bold blue) $directory$git_status$rust$package$python
[â”‚](bold blue)
[â•°â”€$character](bold blue)"""

[character]
success_symbol = "[ï”](bold green)[ï”](bold green)[ï”](bold green)"
error_symbol = "[ï”](bold red)[ï”](bold red)[ï”](bold red)"
vicmd_symbol = "[ï“ï“](bold green)"

[aws]
disabled = true

[time]
disabled = false

[cmd_duration]
disabled = false

[directory]
truncation_length = 5
truncate_to_repo = true
format = "[$path]($style) [$read_only]($read_only_style) "
read_only_style = "197"
read_only = " ï€£ "
repo_root_style = "fg:cyan bold"
repo_root_format = "ï‡’ repo: [$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) â–º "

[hostname]
disabled = false
ssh_only = false
format = "on [$hostname](bold purple)"

[nodejs]
symbol = "ğŸ¤¢"

[battery]
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ï¸ "
discharging_symbol = "ğŸ’€ "
disabled = false

[git_status]
conflicted = "ğŸš©"
ahead = "ğŸ’¨"
behind = "ğŸ˜°"
diverged = "ğŸ˜µ"
untracked = '$count ï '
stashed = "ğŸ“¦"
modified = "$count ğŸ“"
staged = '[+$count](green) '
renamed = "ğŸ‘…"
deleted = "ğŸ’¥"

[shell]
fish_indicator = "ğŸ¦ˆ"
bash_indicator = "ğŸŒ"
powershell_indicator = "ğŸ’»"
disabled = false

[username]
disabled = false
show_always =true
style_root = "red bold"
style_user = "red bold"
format = "[$user]($style) "
